### ISSUE TITLE
Make retarget file

### ISSUE THREAD

**Issue by Lynd-Z** [facebookresearch/AnimatedDrawings#114]
thanks to make awesome code for everyone!

I am testing my own data(bvh), which is made from Rokoko. but I couldn't apply my own .bvh data to retarget.yaml file.

can i get tips for option that making .bvh file? or making retargeting file also?

When I extract code with my own data(.bvh, retarget.yaml, motion.yaml) I got error like this.

```
CRITICAL:root:Could not find BVH joint with name: None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/doubleme/Work/Lyndsey/1_Working/AnimatedDrawings/animated_drawings/render.py", line 21, in start
    scene = Scene(cfg.scene)
  File "/home/doubleme/Work/Lyndsey/1_Working/AnimatedDrawings/animated_drawings/model/scene.py", line 30, in __init__
    ad = AnimatedDrawing(*each)
  File "/home/doubleme/Work/Lyndsey/1_Working/AnimatedDrawings/animated_drawings/model/animated_drawing.py", line 255, in __init__
    self._initialize_retargeter_bvh(motion_cfg, retarget_cfg)
  File "/home/doubleme/Work/Lyndsey/1_Working/AnimatedDrawings/animated_drawings/model/animated_drawing.py", line 317, in _initialize_retargeter_bvh
    self.retargeter = Retargeter(motion_cfg, retarget_cfg)
  File "/home/doubleme/Work/Lyndsey/1_Working/AnimatedDrawings/animated_drawings/model/retargeter.py", line 57, in __init__
    skeleton_fwd: Vectors = self.bvh.get_skeleton_fwd(self.forward_perp_vector_joint_names)
  File "/home/doubleme/Work/Lyndsey/1_Working/AnimatedDrawings/animated_drawings/model/bvh.py", line 115, in get_skeleton_fwd
    assert False, msg
AssertionError: Could not find BVH joint with name: None
```

**Comment by Lynzi-doubleme-me** [comment]
when I extract Rokoko studio, my result is here : 

```python
ROOT Hips
{
  OFFSET 0.0000 94.0000 0.0000
  CHANNELS 6 Xposition Yposition Zposition Yrotation Xrotation Zrotation
  JOINT Spine
  {
    OFFSET 0.0000 8.4839 -3.9483
    CHANNELS 3 Yrotation Xrotation Zrotation
    JOINT Spine1
    {
      OFFSET 7.5932 0.0000 0.0000
      CHANNELS 3 Yrotation Xrotation Zrotation
      JOINT Spine2
      {
        OFFSET 7.5932 0.0000 0.0000
        CHANNELS 3 Yrotation Xrotation Zrotation
        JOINT Spine3
        {
          OFFSET 12.8217 0.0000 0.0000
          CHANNELS 3 Yrotation Xrotation Zrotation
          JOINT LeftShoulder
          {
            OFFSET 12.4389 -7.0401 1.9147
            CHANNELS 3 Yrotation Xrotation Zrotation
            JOINT LeftArm
            {
              OFFSET 13.4599 0.0000 0.0000
              CHANNELS 3 Yrotation Xrotation Zrotation
              JOINT LeftForeArm
              {
                OFFSET 26.1001 0.0000 0.0001
                CHANNELS 3 Yrotation Xrotation Zrotation
                JOINT LeftHand
                {
                  OFFSET 28.9001 0.0000 0.0000
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT LeftHandIndex1
                  {
                    OFFSET 8.0739 -0.1030 2.5612
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT LeftHandIndex2
                    {
                      OFFSET 4.5805 0.0000 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      JOINT LeftHandIndex3
                      {
                        OFFSET 2.8181 0.0000 0.0000
                        CHANNELS 3 Yrotation Xrotation Zrotation
                        End Site
                        {
                          OFFSET 1.3566 0.0000 0.0000
                        }

```  

It is different from repo's joint name. Is that any option in Rokoko studio or any idea?

**Comment by hjessmith** [comment]
> 

Can you share the contents of the `retarget config` file that gave you this error?

**Comment by Lynd-Z** [comment]
[hosi.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11268557/hosi.zip)
@hjessmith here is my yaml file Thanks

**Comment by justinduynguyen** [comment]
i got the same issue :)

**Comment by tiannalu1229** [comment]
me too

**Comment by justinduynguyen** [comment]
this my workaround:
```
char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  - RightHandIndex1
  - RightHandIndex2
  - RightHandIndex3
  - RightHandMiddle1
  - RightHandMiddle2
  - RightHandMiddle3
  - RightHandPinky1
  - RightHandPinky2
  - RightHandPinky3
  - RightHandRing1
  - RightHandRing2
  - RightHandRing3
  - RightHandThumb1
  - RightHandThumb2
  - RightHandThumb3
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - LeftHandIndex1
  - LeftHandIndex2
  - LeftHandIndex3
  - LeftHandMiddle1
  - LeftHandMiddle2
  - LeftHandMiddle3
  - LeftHandPinky1
  - LeftHandPinky2
  - LeftHandPinky3
  - LeftHandRing1
  - LeftHandRing2
  - LeftHandRing3
  - LeftHandThumb1
  - LeftHandThumb2
  - LeftHandThumb3
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - RightUpLeg
  - RightLeg
  - RightFoot
  - RightToeBase
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - LeftToeBase
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Spine
  - Spine1
  - Spine2
  - Neck
  - Head
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftHand
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - RightHand
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - LeftFoot
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightFoot
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightFoot
    - RightLeg
    - RightUpLeg
  - - LeftFoot
    - LeftLeg
    - LeftUpLeg
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - LeftArm
  - LeftForeArm
  left_foot: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_hand: !!python/tuple
  - LeftForeArm
  - LeftHand
  left_knee: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  torso: !!python/tuple
  - Hips
  - Spine2
  neck: !!python/tuple
  - Hips
  - Neck
  right_elbow: !!python/tuple
  - RightArm
  - RightForeArm
  right_foot: !!python/tuple
  - RightLeg
  - RightFoot
  right_hand: !!python/tuple
  - RightForeArm
  - RightHand
  right_knee: !!python/tuple
  - RightUpLeg
  - RightLeg
char_runtime_checks:
  - - above
    - neck
    - right_shoulder
    - left_shoulder
```
rokoko export preset:
![image](https://user-images.githubusercontent.com/18099515/233033489-777f4da5-b03d-4a36-9476-94ff81a3d1ed.png)
edit Frames in bvh file  : n+1
change up in: +y or +z (if one of them not working)
edit end_frame_idx in motion config: n
