### ISSUE TITLE
question about  Adjust animation speed and  bvh  joint  

### ISSUE THREAD

**Issue by yslion** [facebookresearch/AnimatedDrawings#123]
I wait a long time for this open source .  after reading the  guide，I made  own drawings  own bvh and animations . it's ok .
some questions:

the result ,gif or mp4 , is slower than the reference video which i used to generate bvh by rokoko .  how to adjust parameters to fit  the source video speed

all the  bvh files  export from rokoko or down load from somewhere , there are no  LeftHandEnd   RightHandEnd joint  , what did i use wrong?

**Comment by justinduynguyen** [comment]
did you success for custom retarget config and bvh exported from roboko ?
I got a some issue, Can you help me ?
thank u.

```
IERARCHY
ROOT Hips
{
  OFFSET 25.7016 84.0829 0.0000
  CHANNELS 6 Xposition Yposition Zposition Yrotation Xrotation Zrotation
  JOINT Spine
  {
    OFFSET 0.0000 12.9947 0.0000
    CHANNELS 3 Yrotation Xrotation Zrotation
    JOINT Spine1
    {
      OFFSET 0.0000 12.7099 0.0000
      CHANNELS 3 Yrotation Xrotation Zrotation
      JOINT Spine2
      {
        OFFSET 0.0000 12.7829 0.0000
        CHANNELS 3 Yrotation Xrotation Zrotation
        JOINT LeftShoulder
        {
          OFFSET 7.0401 10.4351 1.9147
          CHANNELS 3 Yrotation Xrotation Zrotation
          JOINT LeftArm
          {
            OFFSET 0.0000 13.4599 0.0000
            CHANNELS 3 Yrotation Xrotation Zrotation
            JOINT LeftForeArm
            {
              OFFSET -0.0001 26.1000 0.0000
              CHANNELS 3 Yrotation Xrotation Zrotation
              JOINT LeftHand
              {
                OFFSET 0.0000 28.9001 0.0000
                CHANNELS 3 Yrotation Xrotation Zrotation
                JOINT LeftHandIndex1
                {
                  OFFSET -2.5612 8.0739 0.1030
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT LeftHandIndex2
                  {
                    OFFSET 0.0000 4.5805 0.0000
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT LeftHandIndex3
                    {
                      OFFSET 0.0000 2.8180 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.3566 0.0000
                      }
                    }
                  }
                }
                JOINT LeftHandMiddle1
                {
                  OFFSET -0.5450 8.1365 0.1030
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT LeftHandMiddle2
                  {
                    OFFSET 0.0000 4.7024 0.0000
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT LeftHandMiddle3
                    {
                      OFFSET 0.0000 3.1016 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.4991 0.0000
                      }
                    }
                  }
                }
                JOINT LeftHandPinky1
                {
                  OFFSET 3.1368 7.0181 0.1031
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT LeftHandPinky2
                  {
                    OFFSET 0.0000 3.5540 0.0000
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT LeftHandPinky3
                    {
                      OFFSET 0.0000 2.2339 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.1205 0.0000
                      }
                    }
                  }
                }
                JOINT LeftHandRing1
                {
                  OFFSET 1.4405 7.8067 0.1031
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT LeftHandRing2
                  {
                    OFFSET 0.0000 4.3922 0.0000
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT LeftHandRing3
                    {
                      OFFSET 0.0000 2.8327 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.3500 0.0000
                      }
                    }
                  }
                }
                JOINT LeftHandThumb1
                {
                  OFFSET -2.7863 2.0790 0.0946
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT LeftHandThumb2
                  {
                    OFFSET 0.0000 3.9619 0.0000
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT LeftHandThumb3
                    {
                      OFFSET 0.0000 3.0071 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.7295 0.0000
                      }
                    }
                  }
                }
              }
            }
          }
        }
        JOINT Neck
        {
          OFFSET 0.0000 18.2093 0.0000
          CHANNELS 3 Yrotation Xrotation Zrotation
          JOINT Head
          {
            OFFSET 0.0000 11.0335 0.0000
            CHANNELS 3 Yrotation Xrotation Zrotation
            End Site
            {
              OFFSET 0.0000 8.0220 0.0000
            }
          }
        }
        JOINT RightShoulder
        {
          OFFSET -7.0401 10.4351 1.9147
          CHANNELS 3 Yrotation Xrotation Zrotation
          JOINT RightArm
          {
            OFFSET 0.0000 13.4599 0.0000
            CHANNELS 3 Yrotation Xrotation Zrotation
            JOINT RightForeArm
            {
              OFFSET 0.0000 26.1001 0.0000
              CHANNELS 3 Yrotation Xrotation Zrotation
              JOINT RightHand
              {
                OFFSET -0.0001 28.9001 -0.0001
                CHANNELS 3 Yrotation Xrotation Zrotation
                JOINT RightHandIndex1
                {
                  OFFSET 2.5611 8.0740 0.1030
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT RightHandIndex2
                  {
                    OFFSET 0.0000 4.5805 -0.0001
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT RightHandIndex3
                    {
                      OFFSET 0.0000 2.8180 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.3566 0.0000
                      }
                    }
                  }
                }
                JOINT RightHandMiddle1
                {
                  OFFSET 0.5450 8.1366 0.1030
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT RightHandMiddle2
                  {
                    OFFSET 0.0000 4.7024 -0.0001
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT RightHandMiddle3
                    {
                      OFFSET 0.0000 3.1016 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.4991 0.0000
                      }
                    }
                  }
                }
                JOINT RightHandPinky1
                {
                  OFFSET -3.1368 7.0181 0.1030
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT RightHandPinky2
                  {
                    OFFSET 0.0000 3.5541 -0.0001
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT RightHandPinky3
                    {
                      OFFSET 0.0000 2.2340 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.1205 0.0000
                      }
                    }
                  }
                }
                JOINT RightHandRing1
                {
                  OFFSET -1.4405 7.8068 0.1030
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT RightHandRing2
                  {
                    OFFSET 0.0000 4.3923 -0.0001
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT RightHandRing3
                    {
                      OFFSET 0.0000 2.8327 0.0000
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.3500 0.0000
                      }
                    }
                  }
                }
                JOINT RightHandThumb1
                {
                  OFFSET 2.7863 2.0791 0.0945
                  CHANNELS 3 Yrotation Xrotation Zrotation
                  JOINT RightHandThumb2
                  {
                    OFFSET 0.0000 3.9620 -0.0001
                    CHANNELS 3 Yrotation Xrotation Zrotation
                    JOINT RightHandThumb3
                    {
                      OFFSET 0.0000 3.0072 -0.0001
                      CHANNELS 3 Yrotation Xrotation Zrotation
                      End Site
                      {
                        OFFSET 0.0000 1.7295 0.0000
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  JOINT LeftUpLeg
  {
    OFFSET 8.1000 0.0000 0.0000
    CHANNELS 3 Yrotation Xrotation Zrotation
    JOINT LeftLeg
    {
      OFFSET 0.0000 43.2000 0.0000
      CHANNELS 3 Yrotation Xrotation Zrotation
      JOINT LeftFoot
      {
        OFFSET 0.0000 43.3000 0.0000
        CHANNELS 3 Yrotation Xrotation Zrotation
        JOINT LeftToeBase
        {
          OFFSET 0.0000 14.5727 0.0000
          CHANNELS 3 Yrotation Xrotation Zrotation
          End Site
          {
            OFFSET 0.0000 3.5000 0.0000
          }
        }
      }
    }
  }
  JOINT RightUpLeg
  {
    OFFSET -8.1000 0.0000 0.0000
    CHANNELS 3 Yrotation Xrotation Zrotation
    JOINT RightLeg
    {
      OFFSET 0.0000 43.2000 0.0000
      CHANNELS 3 Yrotation Xrotation Zrotation
      JOINT RightFoot
      {
        OFFSET 0.0000 43.3000 0.0000
        CHANNELS 3 Yrotation Xrotation Zrotation
        JOINT RightToeBase
        {
          OFFSET 0.0000 14.5727 0.0000
          CHANNELS 3 Yrotation Xrotation Zrotation
          End Site
          {
            OFFSET 0.0000 3.5000 0.0000
          }
        }
      }
    }
  }
}
MOTION
Frames: 557
Frame Time: 0.010000
```
and my retarget config
```
char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  - RightHandIndex1
  - RightHandIndex2
  - RightHandIndex3
  - RightHandMiddle1
  - RightHandMiddle2
  - RightHandMiddle3
  - RightHandPinky1
  - RightHandPinky2
  - RightHandPinky3
  - RightHandRing1
  - RightHandRing2
  - RightHandRing3
  - RightHandThumb1
  - RightHandThumb2
  - RightHandThumb3
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - LeftHandIndex1
  - LeftHandIndex2
  - LeftHandIndex3
  - LeftHandMiddle1
  - LeftHandMiddle2
  - LeftHandMiddle3
  - LeftHandPinky1
  - LeftHandPinky2
  - LeftHandPinky3
  - LeftHandRing1
  - LeftHandRing2
  - LeftHandRing3
  - LeftHandThumb1
  - LeftHandThumb2
  - LeftHandThumb3
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - RightUpLeg
  - RightLeg
  - RightFoot
  - RightToeBase
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - LeftToeBase
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Spine
  - Spine1
  - Spine2
  - Neck
  - Head
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftHand
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - RightHand
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - LeftFoot
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightFoot
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightFoot
    - RightLeg
    - RightUpLeg
  - - LeftFoot
    - LeftLeg
    - LeftUpLeg
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - LeftArm
  - LeftForeArm
  left_foot: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_hand: !!python/tuple
  - LeftForeArm
  - LeftHand
  left_knee: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  torso: !!python/tuple
  - Hips
  - Spine3
  neck: !!python/tuple
  - Hips
  - Neck
  right_elbow: !!python/tuple
  - RightArm
  - RightForeArm
  right_foot: !!python/tuple
  - RightLeg
  - RightFoot
  right_hand: !!python/tuple
  - RightForeArm
  - RightHand
  right_knee: !!python/tuple
  - RightUpLeg
  - RightLeg
char_runtime_checks:
  - - above
    - neck
    - right_shoulder
    - left_shoulder
```
but no luck :(
