### ISSUE TITLE
how to change gif size 

### ISSUE THREAD

**Issue by quizD** [facebookresearch/AnimatedDrawings#156]
I want to make the gif`s size is same as origin image, which params or config can control that? ths!!

**Comment by yihleego** [comment]
mvc config: `WINDOW_DIMENSIONS`

```yaml
scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char3/char_cfg.yaml
      motion_cfg: examples/config/motion/dab.yaml
      retarget_cfg: examples/config/retarget/fair1_ppf.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif
view:
  WINDOW_DIMENSIONS: [360, 360]

```
