### ISSUE TITLE
How to speed `GIFWriter` up?

### ISSUE THREAD

**Issue by httzipdev** [facebookresearch/AnimatedDrawings#164]
Hello, 
How can I speed the `GIFWriter` or `VideoWriter` up? 
What criteria or system requirements will this require?
Thank you so much.

**Comment by yihleego** [comment]
Reducing the frames and framerate of BVH is the most effective way as far as I know.
If you are using rokoko to export motions, you can export them as FBX first, 
and then use Blender to edit frames and convert FBX to BVH.

![20230516194228](https://github.com/facebookresearch/AnimatedDrawings/assets/21337386/ba571e56-4b7a-4c8f-b4dd-cf04d83ba5f9)

![image](https://github.com/facebookresearch/AnimatedDrawings/assets/21337386/98a6aeec-6948-4ccb-a9c1-d4abe17c9760)

---

You can also reduce the video/gif dimensions:

```yaml
scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char2/char_cfg.yaml
      motion_cfg: examples/config/motion/dab.yaml
      retarget_cfg: examples/config/retarget/fair1_ppf.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: video.gif
view:
  WINDOW_DIMENSIONS: [ 256, 256 ]

```
