### ISSUE TITLE
Headless, USE_MESA: True within the view section of the config file.   Where exactly?

### ISSUE THREAD

**Issue by xpat** [facebookresearch/AnimatedDrawings#169]
Begin Update ...

Where?  The file is in animated_drawings/mvc_base_cfg.yaml.  

```
scene:
  ADD_FLOOR: False
  ADD_AD_RETARGET_BVH: False
view:
  CLEAR_COLOR: [1.0, 1.0, 1.0, 0.0]
  BACKGROUND_IMAGE: null
  WINDOW_DIMENSIONS: [500, 500]
  DRAW_AD_RIG: False
  DRAW_AD_TXTR: True
  DRAW_AD_COLOR: False
  DRAW_AD_MESH_LINES: False
  USE_MESA: False
  CAMERA_POS: [0.0, 0.7, 2.0]
  CAMERA_FWD: [0.0, 0.5, 2.0]
```
**Change USE_MESA: from False to True**

---- End Update and close issue ---- 

Perhaps the [Headless Rendering section](https://github.com/facebookresearch/AnimatedDrawings#headless-rendering) in the README.md should be expanded?  

There are a number of closed issues that are related to headless renderings:  #96, #99, #158, #167, etc.  Are those even issues if one changes the USE_MESA to true?  Unfortunately I didn't notice the headless instructions until after I'd messed around with other solutions.  But now that I see there's a section on Headless Rendering, I can't find where I'm supposed to change false to true.  

Is it in:
AnimatedDrawings/animated_drawings/config.py?  If so, where, in the Class View section?  or
AnimatedDrawings/animated_drawings/view/view.py or
AnimatedDrawings/animated_drawings/view/mesa_view.py

or somewhere else?  I'm not seeing it (partly because I'm panicking, hahaha).

I just almost successfully ran my first garlic_out test on a Ubuntu 22.04 in the cloud.  Everything but the video was produced, e.g. mask.png, texture.png, bounding_box.yaml, char_cfg.yaml.  Very exciting after a week torturing myself on an inadequately provisioned local machine.
