### ISSUE TITLE
Selecting the Correct YAML File for Wave_Hello.bvh

### ISSUE THREAD

**Issue by donguk071** [facebookresearch/AnimatedDrawings#267]
Hi, your project is really impressive! But I have some questions. 
I want to run wave_hello.bvh and create gif with custom data. I tried using fair1_ppf.yaml and fair_spf.yaml config files for retargeting animation, but I couldn't get the result I expected. I wonder which yaml file I have to use for the retarget_cfg option to run wave_hello.bvh.

Thanks.

**Comment by hjessmith** [comment]
Hi @donguk071 

Two questions for you. First, did you get an animation out of the tool? And second, how did the result differ from what you were expecting? It would be helpful if you uploaded the resulting animation and the character's joint overlay visualization.

**Comment by donguk071** [comment]
Thanks for reply

I used given [animation](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/bvh/fair1/wave_hello.bvh) and [character](https://github.com/facebookresearch/AnimatedDrawings/tree/main/examples/characters/char2) in your repository 

I followed your read.me instruction with this setting

```
sample.yaml

    scene:
      ANIMATED_CHARACTERS:
        - character_cfg: examples/characters/char2/char_cfg.yaml
          motion_cfg: examples/config/motion/wave_hello.yaml
          retarget_cfg: examples/config/retarget/fair1_ppf.yaml
    
    controller:
      MODE: video_render
      OUTPUT_VIDEO_PATH: ./video.gif

```

```
  from animated_drawings import render
  render.start('MyPath/AnimatedDrawings/examples/config/mvc/sample.yaml')
```


And this is result i got, i m expecting more strong? wave like in your [wedsite](https://sketch.metademolab.com/canvas)

![video](https://github.com/facebookresearch/AnimatedDrawings/assets/75608078/8d52ee66-6de8-4f8b-9658-1354731365be)

thanks
